---
- hosts: localhost  
  become: true
  pre_tasks:
    - name: update repositories
      yum: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
  roles:
    - include: roles/extensions.yml
      become_user: elopez