---
- hosts: localhost  
  become: true
  pre_tasks:
    - name: update repositories
      yum: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
- roles: jaredhocutt.gnome_extensions
    vars:
      gnome_extension_ids:
        - 6
        - 906
        - 307     